CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_info (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONSTRAINT user_id FOREIGN KEY (id) REFERENCES users(id),
    name VARCHAR(30),
    surname VARCHAR(40),
    birthday DATETIME
);